CREATE DATABASE colegio;

USE colegio;

CREATE TABLE DOCENTE(
    idDocente INT(100) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombresDocente VARCHAR(30) NOT NULL,
    apellidosDocente VARCHAR(30) NOT NULL,
    contraseñaDocente VARCHAR(8) NOT NULL
    );

CREATE TABLE ESTUDIANTE(
    idEstudiante BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombresEstudiante VARCHAR(30) NOT NULL,
    apellidosEstudiante VARCHAR(30) NOT NULL,
    contraseñaEstudiante VARCHAR(8) NOT NULL
);
CREATE TABLE MATERIA(
    idMateria INT(100) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idDocente INT(100) UNSIGNED NOT NULL,
    nombreMateria VARCHAR(30) NOT NULL,
    cantEstuadiente INT(40) UNSIGNED NOT NULL,
    FOREIGN KEY(idDocente) REFERENCES DOCENTE(idDocente) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MATERIA_INSCRITA(
    idMateria INT(100) UNSIGNED NOT NULL,
    idEstudiante BIGINT UNSIGNED NOT NULL ,
    FOREIGN KEY(idMateria) REFERENCES MATERIA(idMateria) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(idEstudiante) REFERENCES ESTUDIANTE(idEstudiante) ON DELETE CASCADE ON UPDATE CASCADE
);

SHOW TABLES;

DESCRIBE MATERIA;
DESCRIBE DOCENTE;
DESCRIBE ESTUDIANTE;
DESCRIBE MATERIA_INSCRITA;
